Dist m4ri: src/util_io.h File Reference
util_io.h File Reference
#include <inttypes.h>
#include <strings.h>
#include <stdlib.h>
#include <time.h>
#include <stdio.h>
#include <m4ri/m4ri.h>
#include "mmio.h"
#include "util_m4ri.h"
Classes
struct params_t
Macros
#define UTIL_IO_H
#define _maybe_unused __attribute__((unused))
#define USAGE
Functions
void var_init (int argc, char **argv, params_t *const p)
void var_kill (params_t *const p)
Variables
params_t prm
Macro Definition Documentation
_maybe_unused
#define _maybe_unused __attribute__((unused))
Definition at line 21 of file util_io.h.
USAGE
#define USAGE
Value:
  "%s: calculate the minumum distance of a q-LDPC code\n"       \
  "\tusage: %s [arguments [...]]\n"                 \
  "Supported parameters:\n"                     \
  "\tdebug=[int]:\t bitmap for aux information (3)\n"           \
  "\tfin=[string]: base name for input files (\"try\")\n"       \
  "\t\t finH->\"${try}X.mtx\"  finG->\"${try}X.mtx\"\n"         \
  "\tfinH=[str]: parity check matrix Hx (NULL)\n"           \
  "\tfinG=[str]: matrix Hz or NULL for classical code (NULL)\n"     \
  "\tfinL=[str]: matrix Lx or NULL for classical code (NULL)\n"     \
  "\t\t Either L=Lx or G=Hz matrix is required for a quantum CSS code\n" \
  "\tcss=1: this is a CSS code (the only supported one) (1)\n"      \
  "\tseed=[int]: rng seed  [0 for time(NULL)]\n"            \
  "\tmethod=[int]: bitmap for method used: \n"              \
  "\t\t1: random window (RW) algorithm\n"               \
  "\t\t2: cluster (C) algorithm\n"                  \
  "\tsteps=[int]: how many RW decoding cycles to use (1)\n"     \
  "\twmax=[int]: max cluster weight in C (5) \n"            \
  "\twmin=[int]: min distance of interest in RW (1)\n"          \
  "\t-h or --help gives this help\n"
Definition at line 57 of file util_io.h.
UTIL_IO_H
#define UTIL_IO_H
Definition at line 9 of file util_io.h.
Function Documentation
var_init()
void var_init (int argc, char ** argv, params_t *const p)
debug
just assign if in the 1st position
otherwise XOR
finH
< allow space before file name
finL
< allow space before file name
finG degeneracy generator matrix
< allow space before file name
create Lx
WARNING: this does not necessarily have minimal row weights
Definition at line 33 of file util_io.c.
References params_t::classical, csr_mm_read(), params_t::css, params_t::debug, ERROR, params_t::fin, params_t::finG, params_t::finH, params_t::finL, Lx_for_CSS_code(), params_t::method, params_t::n0, params_t::nchk, params_t::nvar, p, csr_t::rows, params_t::seed, params_t::spaG, params_t::spaH, params_t::spaL, params_t::start, params_t::steps, USAGE, params_t::wmax, and params_t::wmin.
var_kill()
void var_kill (params_t *const p)
Definition at line 217 of file util_io.c.
References csr_free(), params_t::fin, params_t::finG, params_t::finH, p, params_t::spaG, params_t::spaH, and params_t::spaL.
Variable Documentation
prm
params_t prm extern
Definition at line 4 of file util_io.c.
Referenced by mzd_generator_from_csr().