Dist m4ri: src/util_m4ri.h File Reference
util_m4ri.h File Reference
Classes
struct csr_t
struct int_pair
Macros
#define SWAPINT(a, b) do{ int t=a; a=b; b=t; } while(0)
#define ERROR(fmt, ...)
#define SETWD(pos) ((pos)>>6)
#define SETBT(pos) ((pos)&0x3F)
#define TIMESWORDSIZE(w) ((w)<<6) /* w*WORDSIZE */
#define FIRSTBIT(x) __builtin_ctzll(x)
Functions
size_t mzd_weight (const mzd_t *A)
size_t mzd_weight_naive (const mzd_t *A)
size_t mzd_weight_row (const mzd_t *A, rci_t i)
rci_t mzd_gauss_naive (mzd_t *M, mzp_t *q, int full)
int csr_max_row_wght (const csr_t *const p)
return max row weight of CSR matrix p TODO: add code for List of Pairs
csr_t * csr_transpose (csr_t *dst, const csr_t *const p)
mzd_t * mzd_from_csr (mzd_t *dst, const csr_t *p)
mzd_t * mzd_generator_from_csr (mzd_t *G, const csr_t *const H)
mzd_t * csr_mzd_mul (mzd_t *C, const csr_t *S, const mzd_t *B, int clear)
mzd_t * syndrome_vector (mzd_t *syndrome, mzd_t *row, csr_t *spaQ, int clear)
size_t product_weight_csr_mzd (const csr_t *A, const mzd_t *B, int transpose)
int rand_uniform (const int max)
mzp_t * mzp_rand_len (mzp_t *q, rci_t length)
void mzp_out (mzp_t const *p)
mzp_t * perm_p (mzp_t *q, const mzp_t *p, rci_t start)
mzp_t * perm_p_trans (mzp_t *q, const mzp_t *p, const rci_t start)
csr_t * csr_free (csr_t *p)
csr_t * csr_init (csr_t *mat, int rows, int cols, int nzmax)
void csr_compress (csr_t *mat)
void csr_out (const csr_t *mat)
void csr_print (const csr_t *const smat, const char str[])
csr_t * csr_mm_read (char *fin, csr_t *mat, int transpose)
csr_t * csr_apply_perm (csr_t *dst, const csr_t *const src, const mzp_t *const perm)
int csr_csr_mul_non_zero (const csr_t *const A, const csr_t *const B)
return 1 if matrix product A*B^T is non-zero
int syndrome_bit_count (const mzd_t *const row, const csr_t *const spaQ)
int do_reduce (mzd_t *row, const mzd_t *matP0, const rci_t rankP0)
void make_err (mzd_t *row, double p)
int do_dist_clus (const csr_t *const P, const mzd_t *const G, int debug, int wmax, int start, const int rankG)
csr_t * Lx_for_CSS_code (const csr_t *const Hx, const csr_t *const Hz)
Compute logical generator matrix Lx for a CSS code.
Macro Definition Documentation
ERROR
#define ERROR (fmt, ...)
Value:
  do{                                                                  \
    fprintf (stderr, "%s:%d: *** ERROR in function '%s()' ***\n", __FILE__, __LINE__, __FUNCTION__); \
    printf("␛[31;1m " fmt "␛[0m\n",##__VA_ARGS__); \
    exit(-1);                                                          \
  }                                                                    \
  while(0)
Definition at line 13 of file util_m4ri.h.
FIRSTBIT
#define FIRSTBIT (x) __builtin_ctzll(x)
Definition at line 32 of file util_m4ri.h.
SETBT
#define SETBT (pos) ((pos)&0x3F)
Definition at line 29 of file util_m4ri.h.
SETWD
#define SETWD (pos) ((pos)>>6)
macros from nauty.h SETWD(pos) gives the setword in which pos is located SETBT(pos) gives the location of bit pos in a setword
Definition at line 28 of file util_m4ri.h.
SWAPINT
#define SWAPINT (a, b) do{ int t=a; a=b; b=t; } while(0)
Definition at line 11 of file util_m4ri.h.
TIMESWORDSIZE
#define TIMESWORDSIZE (w) ((w)<<6) /* w*WORDSIZE */
Definition at line 30 of file util_m4ri.h.
Function Documentation
csr_apply_perm()
csr_t* csr_apply_perm (csr_t * dst, const csr_t *const src, const mzp_t *const perm)
Permute columns of a CSR matrix with permutation perm.
Definition at line 634 of file util_m4ri.c.
References csr_t::cols, csr_compress(), csr_init(), ERROR, csr_t::i, csr_t::nz, csr_t::nzmax, p, csr_t::p, and csr_t::rows.
Referenced by Lx_for_CSS_code().
csr_compress()
void csr_compress (csr_t * mat)
compress a CSR matrix
Definition at line 514 of file util_m4ri.c.
References int_pair::a, int_pair::b, ERROR, csr_t::i, csr_t::nz, and csr_t::p.
Referenced by csr_apply_perm(), csr_mm_read(), and csr_transpose().
csr_csr_mul_non_zero()
int csr_csr_mul_non_zero (const csr_t *const A, const csr_t *const B)
return 1 if matrix product A*B^T is non-zero
Parameters
A first matrix
B second matrix
Definition at line 311 of file util_m4ri.c.
References csr_t::cols, ERROR, csr_t::nz, csr_t::p, and csr_t::rows.
Referenced by var_init().
csr_free()
csr_t* csr_free (csr_t * p)
kill a CSR matrix
Definition at line 461 of file util_m4ri.c.
References p.
Referenced by Lx_for_CSS_code(), and var_kill().
csr_init()
csr_t* csr_init (csr_t * mat, int rows, int cols, int nzmax)
initialize a CSR matrix check existing size and (re)allocate if needded
keep allocated mat
Definition at line 478 of file util_m4ri.c.
References csr_t::cols, ERROR, csr_t::i, csr_t::nz, csr_t::nzmax, csr_t::p, and csr_t::rows.
Referenced by csr_apply_perm(), csr_from_mzd(), csr_mm_read(), and csr_transpose().
csr_max_row_wght()
int csr_max_row_wght (const csr_t *const p)
return max row weight of CSR matrix p TODO: add code for List of Pairs
return max row weight of CSR matrix p TODO: add code for List of Pairs
Definition at line 117 of file util_m4ri.c.
References p.
Referenced by do_CC_dist(), and var_init().
csr_mm_read()
csr_t* csr_mm_read (char * fin, csr_t * mat, int transpose)
read sparse matrix into a (binary) CSR (all entries default to 1) (re)allocate mat if needed use transpose=1 to transpose.
Definition at line 579 of file util_m4ri.c.
References csr_compress(), csr_init(), ERROR, csr_t::i, mm_is_general, mm_is_integer, mm_is_matrix, mm_is_sparse, mm_read_banner(), mm_read_mtx_crd_size(), mm_typecode_to_str(), csr_t::nz, and csr_t::p.
Referenced by var_init().
csr_mzd_mul()
mzd_t* csr_mzd_mul (mzd_t * C, const csr_t * S, const mzd_t * B, int clear)
sparse-S by dense B multiplication C=C+S*B; allocate C if needed.
Definition at line 226 of file util_m4ri.c.
References csr_t::cols, ERROR, csr_t::i, p, csr_t::p, and csr_t::rows.
csr_out()
void csr_out (const csr_t * mat)
output a CSR matrix
Definition at line 540 of file util_m4ri.c.
References csr_t::cols, csr_t::i, csr_t::nz, csr_t::nzmax, p, csr_t::p, and csr_t::rows.
csr_print()
void csr_print (const csr_t *const smat, const char str[])
Definition at line 562 of file util_m4ri.c.
References mzd_from_csr().
Referenced by do_CC_dist(), and var_init().
csr_transpose()
csr_t* csr_transpose (csr_t * dst, const csr_t *const p)
transpose compressed CSR matrix, (re) allocate if needed return resulting matrix TODO: add code for List of Pairs
Definition at line 135 of file util_m4ri.c.
References csr_t::cols, csr_compress(), csr_init(), ERROR, csr_t::i, csr_t::nz, csr_t::nzmax, p, csr_t::p, and csr_t::rows.
Referenced by do_CC_dist().
do_dist_clus()
int do_dist_clus (const csr_t *const P, const mzd_t *const G, int debug, int wmax, int start, const int rankG)
do_reduce()
int do_reduce (mzd_t * row, const mzd_t * matG0, const rci_t rankG0)
Check if row is linearly dependent with the rows of matP0 which is assumed to be in standard form. rankP0 is the number of non-zero rows in rankP0.
Check if row is linearly dependent with the rows of matG0 which is assumed to be in standard form. rankG0 is the number of non-zero rows in rankG0. return: -1 if empty line after simplification otherwise position of the first non-zero bit in the simplified vector
Definition at line 668 of file util_m4ri.c.
Lx_for_CSS_code()
csr_t* Lx_for_CSS_code (const csr_t *const Hx, const csr_t *const Hz)
Compute logical generator matrix Lx for a CSS code.
Given a pair of binary CSS generator matrices in CSR format, Hx*Hz^T=0, compute a sparse matrix Lx s.t. Lx*Hz^T=0 and rows of Lx be linearly independent from those of Hx. TODO: see if sparsity of Lx can be improved.
permute columns to make std form [ I C ]
verify orthogonality
Definition at line 770 of file util_m4ri.c.
References csr_t::cols, csr_apply_perm(), csr_free(), csr_from_mzd(), ERROR, mzd_from_csr(), mzd_gauss_naive(), mzd_generator_from_csr(), perm_p(), perm_p_trans(), product_weight_csr_mzd(), and csr_t::rows.
Referenced by var_init().
make_err()
void make_err (mzd_t * row, double p)
generate binary error vector with error probability p
Definition at line 706 of file util_m4ri.c.
References ERROR, and p.
mzd_from_csr()
mzd_t* mzd_from_csr (mzd_t * dst, const csr_t * p)
Convert CSR sparse binary matrix to MZD allocate dst if needed (must be correct size or NULL)
Definition at line 158 of file util_m4ri.c.
References ERROR, and p.
Referenced by csr_print(), do_RW_dist(), Lx_for_CSS_code(), mzd_generator_from_csr(), and product_weight_csr_mzd().
mzd_gauss_naive()
rci_t mzd_gauss_naive (mzd_t * M, mzp_t * q, int full)
Copy of mzd_gauss_delayed from mzd.c (m4ri package) except additionally returns the list of pivot columns in second argument
Copy of mzd_gauss_delayed from mzd.c (m4ri package) except additionally returns the list of pivot columns in second argument permutation q must be initialized!
Definition at line 76 of file util_m4ri.c.
Referenced by Lx_for_CSS_code(), and mzd_generator_from_csr().
mzd_generator_from_csr()
mzd_t* mzd_generator_from_csr (mzd_t * G, const csr_t *const H)
Convert a sparse binary matrix CSR into a standard form [ I C ], with some col permutations if needed, create the dense generator [ CT I ], and permute the cols back.
(re)allocate G if needed.
Definition at line 185 of file util_m4ri.c.
References csr_t::cols, params_t::debug, mzd_from_csr(), mzd_gauss_naive(), mzp_out(), and prm.
Referenced by Lx_for_CSS_code().
mzd_weight()
size_t mzd_weight (const mzd_t * A)
number of set bits in a matrix.
TODO: use the built-in version for the entire matrix
Definition at line 46 of file util_m4ri.c.
Referenced by csr_from_mzd(), and product_weight_csr_mzd().
mzd_weight_naive()
size_t mzd_weight_naive (const mzd_t * A)
Definition at line 16 of file util_m4ri.c.
mzd_weight_row()
size_t mzd_weight_row (const mzd_t * A, rci_t i)
number of set bits in the row i of a matrix
Definition at line 25 of file util_m4ri.c.
mzp_out()
void mzp_out (mzp_t const * p)
print out the permutation (only needed under windows)
Definition at line 414 of file util_m4ri.c.
References p.
Referenced by mzd_generator_from_csr().
mzp_rand_len()
mzp_t* mzp_rand_len (mzp_t * q, rci_t length)
replace pivot q with a random pivot smaller or equal length (second parameter); remaining positions in place, *** note: LAPACK style pivot permutations! *** return pointer to q. input: perm – existing permutation
Definition at line 398 of file util_m4ri.c.
References ERROR, and rand_uniform().
perm_p()
mzp_t* perm_p (mzp_t * q, const mzp_t * p, rci_t start)
apply pivot p to permutation q in place from start; initialize q to identity permutation if NULL return q
Definition at line 426 of file util_m4ri.c.
References ERROR, p, and SWAPINT.
Referenced by Lx_for_CSS_code().
perm_p_trans()
mzp_t* perm_p_trans (mzp_t * q, const mzp_t * p, const rci_t start)
apply pivot p (transposed) to permutation q in place from start; initialize q to identity permutation if NULL return q
Definition at line 444 of file util_m4ri.c.
References ERROR, p, and SWAPINT.
Referenced by Lx_for_CSS_code().
product_weight_csr_mzd()
size_t product_weight_csr_mzd (const csr_t * A, const mzd_t * B, int transpose)
helper function to compute the weight of the product A*B (transpose == 0) or A*B^T (transpose == 1) with A sparse, B dense binary matrices
Definition at line 358 of file util_m4ri.c.
References mzd_from_csr(), and mzd_weight().
Referenced by Lx_for_CSS_code().
rand_uniform()
int rand_uniform (const int max)
return uniformly distributed random number in the range [0,...,max-1] uses RAND internally
Todo:
Replace by a better generator
return uniformly distributed random number in the range [0,...,max-1]
Definition at line 378 of file util_m4ri.c.
Referenced by mzp_rand_len().
syndrome_bit_count()
int syndrome_bit_count (const mzd_t *const row, const csr_t *const spaQ)
Check whether syndrome is zero or not
just check whether syndrome is zero or not
Definition at line 335 of file util_m4ri.c.
References csr_t::i, p, csr_t::p, and csr_t::rows.
syndrome_vector()
mzd_t* syndrome_vector (mzd_t * syndrome, mzd_t * row, csr_t * spaQ, int clear)
Calculate the syndrome vector change: syndrome=syndrome +row.spaQ optionally clear the destination
Definition at line 283 of file util_m4ri.c.
References csr_t::cols, ERROR, and csr_t::rows.