Dist m4ri: src/util_io.c File Reference
util_io.c File Reference
#include <unistd.h>
#include "util_io.h"
Functions
void var_init (int argc, char **argv, params_t *const p)
void var_kill (params_t *const p)
Variables
params_t prm
params_t *const p = &prm
Function Documentation
var_init()
void var_init (int argc, char ** argv, params_t *const p)
debug
just assign if in the 1st position
otherwise XOR
finH
< allow space before file name
finL
< allow space before file name
finG degeneracy generator matrix
< allow space before file name
create Lx
WARNING: this does not necessarily have minimal row weights
Definition at line 35 of file util_io.c.
References BRIEF_HELP, params_t::classical, csr_t::cols, csr_csr_mul_non_zero(), csr_max_row_wght(), csr_mm_read(), csr_print(), params_t::css, params_t::debug, ERROR, params_t::fin, params_t::finG, params_t::finH, params_t::finL, Lx_for_CSS_code(), params_t::max_row_wgt_H, MAX_W, params_t::method, params_t::n0, params_t::nchk, params_t::nvar, p, csr_t::rows, params_t::seed, params_t::smax, params_t::spaG, params_t::spaH, params_t::spaL, params_t::start, params_t::steps, params_t::swei, USAGE, params_t::wmax, and params_t::wmin.
var_kill()
void var_kill (params_t *const p)
Definition at line 272 of file util_io.c.
References csr_free(), params_t::fin, params_t::finG, params_t::finH, p, params_t::spaG, params_t::spaH, and params_t::spaL.
Variable Documentation
p
params_t* const p = &prm
Definition at line 33 of file util_io.c.
Referenced by csr_free(), csr_max_row_wght(), csr_transpose(), make_err(), mm_read_banner(), mzd_from_csr(), mzp_out(), perm_p(), perm_p_trans(), var_init(), and var_kill().
prm
params_t prm
Initial value:
={
  .debug=3,
  .method=0,
  .classical=0,
  .steps=1,
  .css=1,
  .smax=0,
  .wmax=0,
  .wmin=1,
  .start=-1,
  .seed=0,
  .dist=0,
  .dist_max=0,
  .dist_min=0,
  .max_row_wgt_H =0,
  .max_col_wgt_H =0,
  .n0=0,
  .nvar=0,
  .nchk=0,
  .maxC=0,
  .finH=NULL,
  .finG=NULL,
  .finL=NULL,
  .fin="../examples/try",
  .spaH=NULL,
  .spaG=NULL,
  .spaL=NULL
}
Definition at line 4 of file util_io.c.
Referenced by mzd_generator_from_csr().