name: C/C++ test CI

on:
  push:
    branches: [ "master", "test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # ubuntu-20.04
    # ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd src && sudo apt-get install libm4ri-dev && make -j dist_m4ri
    - name: test
      run: cd src && make test && make run-test
    
