name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # ubuntu-20.04
    # ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libm4ri-dev
    - name: Build
      run: cd src && make -j dist_m4ri
    - name: Run Tests
      run: cd src && make test

